name: Build

on:
  push: 
    branches-ignore: 
      - 'master'

jobs:
  build:

    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: pre-build
      run:  chmod +x ./gradlew
    - name: build
      uses: reactivecircus/android-emulator-runner@v2 
      with:
        api-level: 29
        script: ./gradlew installDebug